-- CreateEnum
CREATE TYPE "ProductUnit" AS ENUM ('GRAM', 'KILOGRAM', 'MILLIGRAM', 'TONNE', 'POUND', 'OUNCE', 'LITER', 'MILLILITER', 'GALLON', 'BARREL', 'CUP', 'TEASPOON', 'TABLESPOON', 'CUBIC_METER', 'CUBIC_FOOT', 'PIECE', 'PACK', 'BAG', 'BOTTLE');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "unit" "ProductUnit" NOT NULL DEFAULT 'KILOGRAM';
